# Backstage ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-service-account
  namespace: default
---
# ClusterRole with necessary permissions for Backstage
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-read-only
rules:
# Core API group resources - FIXED with missing resources
- apiGroups: [""]
  resources: 
    - pods
    - pods/log
    - pods/status
    - services
    - services/status
    - endpoints
    - persistentvolumes
    - persistentvolumeclaims
    - persistentvolumeclaims/status
    - configmaps
    - secrets
    - nodes
    - nodes/status
    - namespaces
    - events
    - serviceaccounts
    - limitranges                    # ADDED - fixes your 403 error
    - resourcequotas                 # ADDED - fixes your 403 error
    - replicationcontrollers
    - replicationcontrollers/status
  verbs: ["get", "list", "watch"]

# Apps API group - FIXED with scale subresources
- apiGroups: ["apps"]
  resources:
    - deployments
    - deployments/status
    - deployments/scale              # ADDED - for scaling information
    - replicasets
    - replicasets/status
    - replicasets/scale              # ADDED - for scaling information
    - statefulsets
    - statefulsets/status
    - statefulsets/scale             # ADDED - for scaling information
    - daemonsets
    - daemonsets/status
  verbs: ["get", "list", "watch"]

# Batch API group (for jobs and cronjobs)
- apiGroups: ["batch"]
  resources:
    - jobs
    - jobs/status
    - cronjobs
    - cronjobs/status
  verbs: ["get", "list", "watch"]

# Extensions API group
- apiGroups: ["extensions"]
  resources:
    - deployments
    - deployments/status
    - replicasets
    - replicasets/status
    - ingresses
    - ingresses/status
  verbs: ["get", "list", "watch"]

# Networking API group
- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
    - ingresses/status
    - networkpolicies
  verbs: ["get", "list", "watch"]

# Autoscaling API group
- apiGroups: ["autoscaling"]
  resources:
    - horizontalpodautoscalers
    - horizontalpodautoscalers/status
  verbs: ["get", "list", "watch"]

# RBAC API group - ADDED for security insights
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - roles
    - rolebindings
    - clusterroles
    - clusterrolebindings
  verbs: ["get", "list", "watch"]

# Policy API group - ADDED
- apiGroups: ["policy"]
  resources:
    - poddisruptionbudgets
    - podsecuritypolicies
  verbs: ["get", "list", "watch"]

# Storage API group - ADDED
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
    - volumeattachments
    - csinodes
    - csidrivers
  verbs: ["get", "list", "watch"]

# Node API group - ADDED
- apiGroups: ["node.k8s.io"]
  resources:
    - runtimeclasses
  verbs: ["get", "list", "watch"]

# Discovery API group - ADDED
- apiGroups: ["discovery.k8s.io"]
  resources:
    - endpointslices
  verbs: ["get", "list", "watch"]

# Coordination API group - ADDED
- apiGroups: ["coordination.k8s.io"]
  resources:
    - leases
  verbs: ["get", "list", "watch"]

# Metrics API group (if using metrics-server)
- apiGroups: ["metrics.k8s.io"]
  resources:
    - pods
    - nodes
  verbs: ["get", "list"]

# Custom Resource Definitions
- apiGroups: ["apiextensions.k8s.io"]
  resources:
    - customresourcedefinitions
  verbs: ["get", "list", "watch"]

# ArgoCD resources (if you use ArgoCD)
- apiGroups: ["argoproj.io"]
  resources:
    - applications
    - applications/status
  verbs: ["get", "list", "watch"]

# Istio resources (if you use Istio)
- apiGroups: ["networking.istio.io"]
  resources:
    - virtualservices
    - destinationrules
    - gateways
  verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding to bind the ClusterRole to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-cluster-reader
subjects:
- kind: ServiceAccount
  name: backstage-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: backstage-read-only
  apiGroup: rbac.authorization.k8s.io

---
# Additional Role for specific namespace access - FIXED with missing resources
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sock-shop
  name: backstage-sock-shop-reader
rules:
- apiGroups: [""]
  resources: 
    - pods
    - pods/log
    - pods/status
    - services
    - services/status
    - endpoints
    - configmaps
    - secrets                        # ADDED
    - events
    - limitranges                    # ADDED - fixes your 403 error
    - resourcequotas                 # ADDED - fixes your 403 error
    - persistentvolumeclaims
    - persistentvolumeclaims/status
    - replicationcontrollers
  verbs: ["get", "list", "watch","delete", "deletecollection"]
- apiGroups: ["apps"]
  resources:
    - deployments
    - deployments/status
    - deployments/scale              # ADDED
    - replicasets
    - replicasets/status
    - replicasets/scale              # ADDED
    - statefulsets
    - statefulsets/status
    - statefulsets/scale             # ADDED
    - daemonsets
    - daemonsets/status
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
    - jobs
    - jobs/status
    - cronjobs
    - cronjobs/status
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]          # ADDED entire section
  resources:
    - horizontalpodautoscalers
    - horizontalpodautoscalers/status
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]    # ADDED entire section
  resources:
    - ingresses
    - ingresses/status
    - networkpolicies
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]               # ADDED entire section
  resources:
    - poddisruptionbudgets
  verbs: ["get", "list", "watch"]

---
# RoleBinding for the specific namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backstage-sock-shop-reader
  namespace: sock-shop
subjects:
- kind: ServiceAccount
  name: backstage-service-account
  namespace: default
roleRef:
  kind: Role
  name: backstage-sock-shop-reader
  apiGroup: rbac.authorization.k8s.io